const interests = [
    "3D printing",
    "Acrobatics",
    "Acting",
    "Amateur radio",
    "Animation",
    "Aquascaping",
    "Astrology",
    "Astronomy",
    "Baking",
    "Baton twirling",
    "Blogging",
    "Building",
    "Board / tabletop games",
    "Book discussion clubs",
    "Book restoration",
    "Bowling",
    "Brazilian jiu - jitsu",
    "Breadmaking",
    "Bullet journaling",
    "Cabaret",
    "Calligraphy",
    "Candle making",
    "Candy making",
    "Car fixing & building",
    "Card games",
    "Cheesemaking",
    "Cleaning",
    "Clothesmaking",
    "Coffee roasting",
    "Collecting",
    "Coloring",
    "Computer programming",
    "Confectionery",
    "Cooking",
    "Cosplaying",
    "Couponing",
    "Craft",
    "Creative writing",
    "Crocheting",
    "Cross - stitch",
    "Crossword puzzles",
    "Cryptography",
    "Cue sports",
    "Dance",
    "Digital arts",
    "Distro Hopping",
    "DJing",
    "Do it yourself",
    "Drama",
    "Drawing",
    "Drink mixing",
    "Electronic games",
    "Electronics",
    "Embroidery",
    "Experimenting",
    "Fantasy sports",
    "Fashion",
    "Fashion design",
    "Fishkeeping",
    "Filmmaking",
    "Flower arranging",
    "Fly tying",
    "Foreign language learning",
    "Furniture building",
    "Gaming(tabletop games and role - playing games)",
    "Genealogy",
    "Gingerbread house making",
    "Glassblowing",
    "Graphic design",
    "Gunsmithing",
    "Gymnastics",
    "Hacking",
    "Herp keeping",
    "Home improvement",
    "Homebrewing",
    "Houseplant care",
    "Hula hooping",
    "Humor",
    "Hydroponics",
    "Ice skating",
    "Jewelry making",
    "Jigsaw puzzles",
    "Journaling",
    "Juggling",
    "Karaoke",
    "Karate",
    "Kendama",
    "Knife making",
    "Knitting",
    "Knot tying",
    "Kombucha brewing",
    "Lace making",
    "Lapidary",
    "Leather crafting",
    "Lego building",
    "Lock picking",
    "Listening to music",
    "Listening to podcasts",
    "Machining",
    "Macrame",
    "Magic",
    "Makeup",
    "Mazes(indoor / outdoor)",
    "Metalworking",
    "Model building",
    "Model engineering",
    "Nail art",
    "Needlepoint",
    "Origami",
    "Painting",
    "Palmistry",
    "Pet adoption & fostering",
    "Philately",
    "Photography",
    "Practical jokes",
    "Pressed flower craft",
    "Playing musical instruments",
    "Poi",
    "Pottery",
    "Powerlifting",
    "Puzzles",
    "Quilling",
    "Quilting",
    "Quizzes",
    "Radio - controlled model",
    "Rail transport modeling",
    "Rapping",
    "Reading",
    "Refinishing",
    "Reiki",
    "Robot combat",
    "Rubik's Cube",
    "Scrapbooking",
    "Sculpting",
    "Sewing",
    "Shoemaking",
    "Singing",
    "Sketching",
    "Skipping rope",
    "Slot car",
    "Soapmaking",
    "Social media",
    "Spreadsheets",
    "Stand - up comedy",
    "Stamp collecting",
    "Table tennis",
    "Tarot",
    "Taxidermy",
    "Thrifting",
    "Video editing",
    "Video game developing",
    "Video gaming",
    "Watching movies",
    "Watching television",
    "Videography",
    "Waxing",
    "Weaving",
    "Weight training",
    "Welding",
    "Whittling",
    "Wikipedia editing",
    "Winemaking",
    "Wood carving",
    "Woodworking",
    "Worldbuilding",
    "Writing",
    "Word searches",
    "Yo - yoing",
    "Yoga",
    "Zumba",
    "Outdoors",
    "Air sports",
    "Airsoft",
    "Archery",
    "Astronomy",
    "Backpacking",
    "BASE jumping",
    "Baseball",
    "Basketball",
    "Beekeeping",
    "Birdwatching",
    "Blacksmithing",
    "BMX",
    "Board sports",
    "Bodybuilding",
    "Bonsai",
    "Butterfly watching",
    "Camping",
    "Canoeing",
    "Canyoning",
    "Caving",
    "Composting",
    "Cycling",
    "Dowsing",
    "Driving",
    "Fishing",
    "Flag football",
    "Flower growing",
    "Flying",
    "Flying disc",
    "Foraging",
    "Fossicking",
    "Freestyle football",
    "Gardening",
    "Geocaching",
    "Ghost hunting",
    "Gold prospecting",
    "Graffiti",
    "Handball",
    "Herbalism",
    "Herping",
    "High - power rocketry",
    "Hiking",
    "Hobby horsing",
    "Hobby tunneling",
    "Hooping",
    "Horseback riding",
    "Hunting",
    "Inline skating",
    "Jogging",
    "Jumping rope",
    "Kayaking",
    "Kite flying",
    "Kitesurfing",
    "Lacrosse",
    "LARPing",
    "Letterboxing",
    "Longboarding",
    "Martial arts",
    "Metal detecting",
    "Meteorology",
    "Motor sports",
    "Mountain biking",
    "Mountaineering",
    "Mushroom hunting / mycology",
    "Netball",
    "Nordic skating",
    "Orienteering",
    "Paintball",
    "Parkour",
    "Photography",
    "Podcast hosting",
    "Polo",
    "Rafting",
    "Rappelling",
    "Road biking",
    "Rock climbing",
    "Roller skating",
    "Rugby",
    "Running",
    "Radio - controlled model",
    "Sailing",
    "Sand art",
    "Scouting",
    "Scuba diving",
    "Sculling or rowing",
    "Shooting",
    "Shopping",
    "Shuffleboard",
    "Skateboarding",
    "Skiing",
    "Skimboarding",
    "Skydiving",
    "Slacklining",
    "Snowboarding",
    "Snowmobiling",
    "Snowshoeing",
    "Soccer",
    "Stone skipping",
    "Sun bathing",
    "Surfing",
    "Survivalism",
    "Swimming",
    "Taekwondo",
    "Tai chi",
    "Tennis",
    "Topiary",
    "Thru - hiking",
    "Travel",
    "Urban exploration",
    "Vacation",
    "Vegetable farming",
    "Videography",
    "Vehicle restoration",
    "Walking",
    "Water sports",
    "Collection hobbies",
    "Indoors",
    "Action figure",
    "Antiquing",
    "Art collecting",
    "Book collecting",
    "Button collecting",
    "Cartophily(card collecting)",
    "Coin collecting",
    "Comic book collecting",
    "Deltiology(postcard collecting)",
    "Die - cast toy",
    "Dolls",
    "Element collecting",
    "Ephemera collecting",
    "Fusilately(phonecard collecting)",
    "Knife collecting",
    "Lotology(lottery ticket collecting)",
    "Movie and movie memorabilia collecting",
    "Perfume",
    "Phillumeny",
    "Pin(lapel)",
    "Radio - controlled model",
    "Rail transport modelling",
    "Record collecting",
    "Rock tumbling",
    "Scutelliphily",
    "Shoes",
    "Slot car",
    "Sports memorabilia",
    "Stamp collecting",
    "Stuffed toy collecting",
    "Tea bag collecting",
    "Ticket collecting",
    "Toys",
    "Video game collecting",
    "Vintage cars",
    "Vintage clothing",
    "Vinyl Records",
    "Outdoors",
    "Antiquities",
    "Auto audiophilia",
    "Flower collecting and pressing",
    "Fossil hunting",
    "Insect collecting",
    "Magnet fishing",
    "Metal detecting",
    "Mineral collecting",
    "Rock balancing",
    "Sea glass collecting",
    "Seashell collecting",
    "Stone collecting",
    "Competitive hobbies",
    "Indoors",
    "Animal fancy",
    "Axe throwing",
    "Backgammon",
    "Badminton",
    "Baton twirling",
    "Beauty pageants",
    "Billiards",
    "Bowling",
    "Boxing",
    "Bridge",
    "Checkers(draughts)",
    "Cheerleading",
    "Chess",
    "Color guard",
    "Cribbage",
    "Curling",
    "Dancing",
    "Darts",
    "Debate",
    "Dominoes",
    "Eating",
    "Esports",
    "Fencing",
    "Go",
    "Gymnastics",
    "Ice hockey",
    "Ice skating",
    "Judo",
    "Jujitsu",
    "Kabaddi",
    "Knowledge / word games",
    "Laser tag",
    "Longboarding",
    "Mahjong",
    "Marbles",
    "Martial arts",
    "Model racing",
    "Model United Nations",
    "Poker",
    "Pool",
    "Role - playing games",
    "Shogi",
    "Slot car racing",
    "Speedcubing",
    "Sport stacking",
    "Table football",
    "Table tennis",
    "Volleyball",
    "Weightlifting",
    "Wrestling",
    "Outdoors",
    "Airsoft",
    "American football",
    "Archery",
    "Association football",
    "Australian rules football",
    "Auto racing",
    "Baseball",
    "Beach volleyball",
    "Breakdancing",
    "Climbing",
    "Cricket",
    "Croquet",
    "Cycling",
    "Disc golf",
    "Dog sport",
    "Equestrianism",
    "Exhibition drill",
    "Field hockey",
    "Figure skating",
    "Fishing",
    "Footbag",
    "Frisbee",
    "Golfing",
    "Handball",
    "Horseback riding",
    "Horseshoes",
    "Iceboat racing",
    "Jukskei",
    "Kart racing",
    "Knife throwing",
    "Lacrosse",
    "Longboarding",
    "Long - distance running",
    "Marching band",
    "Model aircraft",
    "Orienteering",
    "Powerboat racing",
    "Quidditch",
    "Race walking",
    "Racquetball",
    "Radio - controlled car racing",
    "Roller derby",
    "Rugby league football",
    "Sculling or rowing",
    "Shooting sport",
    "Skateboarding",
    "Skiing",
    "Sled dog racing",
    "Softball",
    "Speed skating",
    "Squash",
    "Surfing",
    "Swimming",
    "Table tennis",
    "Tennis",
    "Tennis polo",
    "Tether car",
    "Tour skating",
    "Trapshooting",
    "Triathlon",
    "Ultimate frisbee",
    "Volleyball",
    "Water polo",
    "Observation hobbies",
    "Indoors",
    "Fishkeeping",
    "Learning",
    "Meditation",
    "Microscopy",
    "Reading",
    "Research",
    "Shortwave listening",
    "Audiophile",
    "Videophilia",
    "Outdoors",
    "Aircraft spotting",
    "Amateur astronomy",
    "Birdwatching",
    "Bus spotting",
    "Geocaching",
    "Gongoozling",
    "Herping",
    "Hiking / backpacking",
    "Meteorology",
    "Photography",
    "Satellite watching",
    "Trainspotting",
    "Traveling",
    "Walking",
    "Whale watching"
];

module.exports = interests;
